---
title: "Weekly Summary 3"
author: "Alvaro Tapia"
title-block-banner: true
title-block-style: default
toc: true
format: html
# format: pdf
---

---

## Tuesday, Jan 24

::: {.callout-important}
## TIL

In this class we first started learning about how does a csv file looks like and also how to read csv files in R. Then we learned how useful the packages such as "ggplot2" and "dplyr" are for exploratory data analysis. Finally we learned how to clean a csv file o a data sources/set.

Today, I learnt the following concepts in class:

1. Learned how to read csv files, using: File_location <- “./data/data.csv” and Data_from.csv <- read.csv(file_location)

2. We learned what "dplyr" and "ggplot2" packages d, such as trend lines, creating color for species, and more.

3. We learned how to clean a dataset, for example. Getting rid of the NULL, NA, NaN variables, making sure all the particular variable data types are the same, and that every variable has its own column.

:::

Here it's an example of using ggplo2

```{R results='hide'}
#| output: false
library(ggplot2)
head(mpg,5) %>% knitr::kable()
head(iris,5) %>% knitr::kable()
```


## Thursday, Jan 26



::: {.callout-important}
## TIL

In this class we did a lot of things, first we started installing again ggplot2, but now we included the package "ggThemesAssist". After that, we also started talking about the package "broom" which is used to clean dataframes and datasets. We also recalled what we learned about data types, such as string, integers, double and boolean. Basically we learned about more packages and their functionality and did some exercises.


Today, I learnt the following concepts in class:

1. Learned how to install and use ggplot2, ggThemeAssist, and broom.
2. Then we learned about the “forcats” package 
3. Then we learned about the “purr” package. This package provides a set of functional programing tools. 
:::

Here are some examples of using the first packages described.

```{R results='hide'}
library(ggplot2)
library(ggThemeAssist)
As.factor(iris)
Iris$Species
Head(mp, 3) %>% Knits::Kable
```

Examples using the library forcats

```{R results='hide'}
Library(forcats)
Manufacturer <- as.factor(mpg$manufacturer)
Fct_reorder(manufacturer, mpg$my, min)
```

Finding the average pf ‘Sepal.Area’ for every flower in the species:

```{R results='hide'}
Iris %>%
Mutate(Area = Sepal.Length * Sepal.Width) %>%
Group.by()
Summarize()
```

After that we created a matrix with random entries of dimension ‘I’ $\times$ ‘I’ and then we computed the average of the elements of the matrix. However I was unable to keep track of the code.


[^footnote]: I'm missing some examples because even though I tried to take pictures of the class because everything was being typed very fast it was blurry because I sat at the back, the next weekly summary will have everything included.
